msg_long_prefix: "&8-*-*-*-*-*-*-*-*- &7-=[ &fThe &bFloating &aCity &7]=- &8-*-*-*-*-*-*-*-*-"
msg_prefix: "&7[&fT&bF&aC&7]&r "
msg_motd: "&fWelcome back! The last time you were on was &e%s &f%s ago."
msg_welcome: "&fWelcome to the server, %s! Let me give you a quick tour."

spawn:
  X: 0.5
  Y: 60
  Z: 0.5

msg_no_build: "&fYou aren't allowed to build! Please accept the rules first via &e/rules&f!"

msg_gamemode_change: "&fYour gamemode has been changed to &e%s&f!"

msg_fly_enabled: "&fYou can now fly! Remember, only for super emergencies. If you're using it outside of an emergency I will &oPERSONALLY SMITE YOU, &c&lYOU HEAR ME? &rOkay thank you!"
msg_fly_disabled: "&fThanks for disabling it. It's disabled."

msg_join: "&f%s joined the game."
msg_leave: "&f%s left the game."

msg_not_online: "&fThat player is not online."
msg_player_only: "&fYou must be a player to use this command."

msg_hat_set: "&fNow that's a fancy hat!"
msg_hat_removed: "&fGot your hat! I removed it. That's what I did."
msg_hat_none: "&fTo put on a hat, hold what you want to wear!"

msg_shrug: "&f%s &ashrugs \\_o¬o_/"
msg_blame: "&f%s &cblames &f%s"
msg_sue: "&f%s &cis suing &f%s"

msg_zap: "&f%s &czapped &f%s"
msg_zap_themself: "&f%s &czapped &fthemself"
msg_zap_everyone: "&f%s &czapped &feveryone"

msg_launch: "&f%s &alaunched &f%s"
msg_launch_themself: "&f%s &alaunched &fthemselves"
msg_launch_everyone: "&f%s &alaunched &feveryone"

msg_poke: "&f%s &cpoked &f%s"
msg_poke_themself: "&f%s &cpoked &fthemselves"
msg_poke_everyone: "&f%s &cpoked &feveryone"
poke_force:
  maxY: 0.8
  minY: 0.2
  maxXZ: 0.8
  minXZ: -0.8

msg_warp_first: "&fReaching maximum &6warp speed&f.."
msg_warp_second: "&fReaching maximum &cwarp speed&f.."
msg_warp_max: "&fMaximum &4warp speed &freached!"



