##########
#        #
#  MISC  #
#        #
##########
tfc_banner: "&8-*-*-*-*-*-*-*-*- &7-=[&f The &bFloating &aCity &7]=- &8-*-*-*-*-*-*-*-*-"
tfc_prefix: "&7[&fT&bF&aC&7]&f"
tfc_multi: "&b&l>"

msg_motd: "&fWelcome back! You were last on &e%s&f %s ago."
msg_welcome: "&fWelcome to &aThe Floating City&f, &e%s&f!"

msg_join: "&7[&a+&7]&f &f%s joined the game."
msg_leave: "&7[&c-&7]&f &f%s left the game."

chat_format: "&f{prefix}&f &7%1$s&f{suffix}&f: %2$s"

msg_not_online: "&fThat player isn't online."
msg_player_only: "&fYou must be a player to use this command."

msg_no_build: "&fYou can't build! Please read our rules first by doing &e/rules&f!"

spawn:
  world: world
  x: 0.5
  y: 60
  z: 0.5

msg_warp_first: "&fReaching maximum &6warp speed&f.."
msg_warp_second: "&fReaching maximum &cwarp speed&f.."
msg_warp_max: "&fMaximum &4warp speed&f reached!"

############
#          #
#  ACTION  #
#          #
############
msg_zap: "&f%s &czapped&f %s"
msg_zap_themself: "&f%s &czapped&f themselves"

msg_launch: "&f%s &alaunched&f %s"
msg_launch_themself: "&f%s &alaunched&f themselves"

msg_boost: "&f%s &aboosted&f %s"
msg_boost_themself: "&f%s &aboosted&f themselves"

msg_poke: "&f%s &cpoked&f %s"
msg_poke_themself: "&f%s &cpoked&f themselves"
poke_force:
  maxY: 0.8
  minY: 0.2
  maxXZ: 0.8
  minXZ: -0.8

##########
#        #
#  CORE  #
#        #
##########
msg_reloaded: "&fConfig reloaded successfully!"

###########
#         #
#  EMOTE  #
#         #
###########
emote_winkwonk: "&d%s &5wink wonks &d;)"
emote_shrug: "&a%s &2shrugs &a\\_o¬o_/"
emote_doubt: "&b%s &9doubts that."
emote_blame: "&c%s &4blames &c%s"
emote_sue: "&e%s &6is suing &e%s"


##############
#            #
#  GAMEMODE  #
#            #
##############
msg_gamemode_unknown: "&fPlease enter a valid gamemode! Such as &esurvival&f, &es&f, &e0&f, &ecreative&f, &ec&f, &e1&f, &eadventure&f, &ea&f, or &e2&f."
msg_gamemode_changed: "&fYour gamemode has been changed to &e%s&f!"
msg_gamemode_changed_other: "&6%s&f's gamemode has been changed to &e%s&f!"

###########
#         #
#  PIANO  #
#         #
###########
piano_prefix: "&7[&3Piano&7]&f"
piano_multi: "&3&l>"

msg_piano_help: "&fFirst, do &e/piano menu&f and pick out any notes you would like to play, and put them into your hotbar. Right clicking the notes while in the menu plays them. If you want a nice selection of notes, pick all of them that are marked as &eF# Major&f! Next, if you want to change the default instrument, you can use &e/piano instrument&f to pick an instrument you would like. Tab completion works too! Finally, do &e/piano toggle&f and then if you change your selected hotbar item to the slot the note is on, it'll play that note! Have fun!"
msg_piano_enabled: "&aThe piano is now enabled!"
msg_piano_disabled: "&cThe piano is now disabled. &fHope you enjoyed!"
msg_piano_instrument_change: "&fYour piano instrument is now set to &e%s&f!"
piano_notes_inventory_name: "Piano Notes"
piano_notes:
  piano_note1:
    name: "&fF♯/G♭ [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Major, F# Minor&f]"
      - "&8[Note]"
      - "0.5"
    data: 8
  piano_note2:
    name: "&fG [&bOctave 1&f]"
    lore:
      - "&7Part of&f []"
      - "&8[Note]"
      - "0.529732"
    data: 0
  piano_note3:
    name: "&fG♯/A♭ [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Major, F# Minor&f]"
      - "&8[Note]"
      - "0.561231"
    data: 8
  piano_note4:
    name: "&fA [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Minor&f]"
      - "&8[Note]"
      - "0.594604"
    data: 0
  piano_note5:
    name: "&fA♯/B♭ [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Major&f]"
      - "&8[Note]"
      - "0.629961"
    data: 8
  piano_note6:
    name: "&fB [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Major, F# Minor&f]"
      - "&8[Note]"
      - "0.667420"
    data: 0
  piano_note7:
    name: "&fC [&bOctave 1&f]"
    lore:
      - "&7Part of&f []"
      - "&8[Note]"
      - "0.707107"
    data: 0
  piano_note8:
    name: "&fC♯/D♭ [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Major, F# Minor&f]"
      - "&8[Note]"
      - "0.749154"
    data: 8
  piano_note9:
    name: "&fD [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Minor&f]"
      - "&8[Note]"
      - "0.793701"
    data: 0
  piano_note10:
    name: "&fD♯/E♭ [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Major&f]"
      - "&8[Note]"
      - "0.840896"
    data: 8
  piano_note11:
    name: "&fE [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Minor&f]"
      - "&8[Note]"
      - "0.890899"
    data: 0
  piano_note12:
    name: "&fF [&bOctave 1&f]"
    lore:
      - "&7Part of&f [&eF# Major&f]"
      - "&8[Note]"
      - "0.943874"
    data: 0
  piano_note13:
    name: "&fF♯/G♭ [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Major, F# Minor&f]"
      - "&8[Note]"
      - "1"
    data: 8
  piano_note14:
    name: "&fG [&bOctave 2&f]"
    lore:
      - "&7Part of&f []"
      - "&8[Note]"
      - "1.059463"
    data: 0
  piano_note15:
    name: "&fG♯/A♭ [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Major, F# Minor&f]"
      - "&8[Note]"
      - "1.122462"
    data: 8
  piano_note16:
    name: "&fA [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Minor&f]"
      - "&8[Note]"
      - "1.189207"
    data: 0
  piano_note17:
    name: "&fA#/B♭ [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Major&f]"
      - "&8[Note]"
      - "1.259921"
    data: 8
  piano_note18:
    name: "&fB [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Major, F# Minor&f]"
      - "&8[Note]"
      - "1.334840"
    data: 0
  piano_note19:
    name: "&fC [&bOctave 2&f]"
    lore:
      - "&7Part of&f []"
      - "&8[Note]"
      - "1.414214"
    data: 0
  piano_note20:
    name: "&fC♯/D♭ [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Major, F# Minor&f]"
      - "&8[Note]"
      - "1.498307"
    data: 8
  piano_note21:
    name: "&fD [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Minor&f]"
      - "&8[Note]"
      - "1.587401"
    data: 0
  piano_note22:
    name: "&fD♯/E♭ [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Major&f]"
      - "&8[Note]"
      - "1.681793"
    data: 8
  piano_note23:
    name: "&fE [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Minor&f]"
      - "&8[Note]"
      - "1.781797"
    data: 0
  piano_note24:
    name: "&fF [&bOctave 2&f]"
    lore:
      - "&7Part of&f [&eF# Major&f]"
      - "&8[Note]"
      - "1.887749"
    data: 0
  piano_note25:
    name: "&fF♯/G♭ [&bOctave 3&f]"
    lore:
      - "&7Part of&f [&eF# Major, F# Minor&f]"
      - "&8[Note]"
      - "2"
    data: 8

###########
#         #
#  RULES  #
#         #
###########
rules_prefix: "&7[&cRules&7]&f"
rules_multi: "&c&l>"

msg_rules: "&f%s &7| Page &e%s&7/&e9"
msg_rules_help: "&cInvalid page number. &fTry numbers &e1&7-&e9&f."
msg_rules_accept: "&fThanks for reading the rules! Here's your passenger."
msg_rules_already_accepted: "&fLooks like you've already read the rules, thanks!"
rules:
  rule1:
    topic: "Griefing"
    content:
      - "&fNo touching other people's stuff without their permission."
      - "&fThis includes placing or breaking blocks,"
      - "&ftaking or placing items in their chests, taking or placing items in their itemframes,"
      - "&ftrampling their crops, killing their animals.. You get the idea."
      - "&fPlease use common sense. If it isn't yours, leave it be."
  rule2:
    topic: "Swearing"
    content:
      - "&fSwearing is allowed but please try to be courteous."
      - "&fRemember, as much as you may think otherwise, Minecraft is"
      - "&fa kids game and there are kids who play it."
      - "&fSo please just don't fill up the chat with a bunch of swearing."
  rule3:
    topic: "Spamming"
    content:
      - "&fHaving long messages and lots of them is fine, but please"
      - "&fdon't fill up chat with meaningless gibberish,"
      - "&for repeat the same messages over and over. Again, please"
      - "&fbe courteous and mindful of other people."
  rule4:
    topic: "Advertising"
    content:
      - "&fWe're a pretty unconvential server! Talking about servers,"
      - "&fsaying their names, even putting their IPs is fine."
      - "&fJust no advertising any servers trying to get random people on it,"
      - "&fThere are websites for that, you know. If you're asking a friend if they wanna go on"
      - "&fthis server and they forgot the IP, it's fine."
  rule5:
    topic: "Hurtful Speech"
    content:
      - "&fNo hate speech or discrimination or insults against anyone."
      - "&fWe're not a politically correct server but don't be a jerk."
      - "&fIf something you say might hurt someone, don't say it."
  rule6:
    topic: "Flamewars"
    content:
      - "&fHaving discussions about things are fine! Religion, politics, so be it."
      - "&fHowever, keep it cool and a debate, not a flamewar."
      - "&fAlso, be mindful of Rule 5. If you feel like talking about something"
      - "&fthat might hurt someone, don't talk about it with them."
      - "&fBut if you both want to talk about it and engage in discussion, it's fine!"
  rule7:
    topic: "PG-13"
    content:
      - "&fWe're a pretty relaxed server. But keep it PG-13."
      - "&fNo builds or chat that has a lot of gore or sexual content."
      - "&fIf you wouldn't see it in Avengers, don't make it please."
  rule8:
    topic: "Lag, Bugs, and Glitches"
    content:
      - "&fPlease don't try to break a server. It's not funny."
      - "&fYou're not a hacker, it just ruins the game we're all trying to"
      - "&fhave fun and play on. This means no lag machines or"
      - "&fgiant super big repeating complex redstone, and if you find"
      - "&fany bugs or glitches, please report them to staff! Thanks!"
  rule9:
    topic: "Golden Rule"
    content:
      - "&fIf you forget even everything, remember this golden rule."
      - "&fDon't be a jerk, and use common sense. This one golden rule"
      - "&fwill happily keep you playing on the server."
      - "&fAs long as you're not a jerk towards anyone, and you use common sense,"
      - "&flike not griefing builds, not spamming chat, etc, you'll be golden!"

##########
#        #
#  UTIL  #
#        #
##########
msg_fly_enabled: "&fYou can now fly! Please only use this in emergencies when you need to get somewhere high up."
msg_fly_disabled: "&fYou can no longer fly. Thanks for disabling it!"

msg_hat_set: "&fNow that's a fancy hat!"
msg_hat_removed: "&fAww, there goes your fancy hat."
msg_hat_none: "&fTo put on a hat, hold what you want to wear!"

blocks_inventory_name: "Useful Building Blocks"
blocks:
  block1:
    name: "&fBrown Mushroom Block"
    material: "HUGE_MUSHROOM_1"
    data: 0
  block2:
    name: "&fRed Mushroom Block"
    material: "HUGE_MUSHROOM_2"
    data: 0
  block3:
    name: "&fGrass Path"
    material: "GRASS_PATH"
    data: 0
  block4:
    name: "&fDragon Egg"
    material: "DRAGON_EGG"
    data: 0
  block5:
    name: "&fFarmland"
    material: "SOIL"
    data: 0
