msg_prefix_long: "&8-*-*-*-*-*-*-*-*- &7-=[ &fThe &bFloating &aCity &7]=- &8-*-*-*-*-*-*-*-*-"
msg_prefix: "&7[&fT&bF&aC&7]&r "
msg_motd: "&fWelcome back! The last time you were on was &e%s &f%s ago."
msg_welcome: "&fWelcome to the server, %s! Let me give you a quick tour."

spawn:
  world: world
  x: 0.5
  y: 60
  z: 0.5

golden_rule: "The holy &eGolden Rule&f!"
rules_prefix_long: "-*-*-*-*-*-*-*-*-*-* -=[ The Rules ]=- *-*-*-*-*-*-*-*-*-*-"
rules_inventory_name: "Rules | The Floating City"
msg_rules: "&fThis is a test message. Rules are coming soon! :)"
msg_rules_help: "&fThis is a test message. Help is coming soon! :)"
msg_rules_accept: "&fThanks! You can now build. Go have fun! :D"
rules:
  rule1:
    name: "Rule 1 | Griefing"
    text: ["&rNo touching other people's stuff without their permission.", "This includes placing or breaking blocks,", "taking or placing items in their chests, taking or placing items in their itemframes,", "trampling their crops, killing their animals.. You get the idea.", "Please use common sense. If it isn't yours, leave it be."]
  rule2:
    name: "Rule 2 | Swearing"
    text: ["Swearing is allowed but please try to be courteous.", "Remember, as much as you may think otherwise, Minecraft is", "a kids game and there are kids who play it.", "So please just don't fill up the chat with a bunch of swearing."]
  rule3:
    name: "Rule 3 | Spamming"
    text: ["Having long messages and lots of them is fine, but please", "don't fill up chat with meaningless gibberish,", "or repeat the same messages over and over. Again, please", "be courteous and mindful of other people."]
  rule4:
    name: "Rule 4 | Advertising"
    text: ["We're a pretty unconvential server! Talking about servers,", "saying their names, even putting their IPs is fine.", "Just no advertising any servers trying to get random people on it,", "There are websites for that, you know. If you're asking a friend if they wanna go on", "this server and they forgot the IP, it's fine."]
  rule5:
    name: "Rule 5 | Hurtful Speech"
    text: ["No hate speech or discrimination or insults against anyone.", "We're not a politically correct server but don't be a jerk.", "If something you say might hurt someone, don't say it."]
  rule6:
    name: "Rule 6 | Flamewars"
    text: ["Having discussions about things are fine! Religion, politics, so be it.", "However, keep it cool and a debate, not a flamewar.", "Also, be mindful of Rule 5. If you feel like talking about something", "that might hurt someone, don't talk about it with them.", "But if you both want to talk about it and engage in discussion, it's fine!"]
  rule7:
    name: "Rule 7 | PG-13"
    text: ["We're a pretty relaxed server. But keep it PG-13.", "No builds or chat that has a lot of gore or sexual content.", "If you wouldn't see it in Avengers, don't make it please."]
  rule8:
    name: "Rule 8 | Lag, Bugs, and Glitches"
    text: ["Please don't try to break a server. It's not funny.", "You're not a hacker, it just ruins the game we're all trying to", "have fun and play on. This means no lag machines or", "giant super big repeating complex redstone, and if you find", "any bugs or glitches, please report them to staff! Thanks!"]
  rule9:
    name: "Rule 9 | Golden Rule"
    text: ["If you forget even everything, remember this golden rule.", "Don't be a jerk, and use common sense. This one golden rule", "will happily keep you playing on the server.", "As long as you're not a jerk towards anyone, and you use common sense,", "like not griefing builds, not spamming chat, etc, you'll be golden!"]

msg_no_build: "&fYou can't build! Please accept the rules first by doing &e/rules&f!"

msg_help: "&fThis is a test message. Help is coming soon! :)"
msg_action_help: "&fThis is a test message. Help is coming soon! :)"
msg_emote_help: "&fThis is a test message. Help is coming soon! :)"
msg_util_help: "&fThis is a test message. Help is coming soon! :)"

msg_gamemode_help: "&fChange your gamemode! You can use /gmc or /gamemode 1/c/creative for creative, and so on for the rest.!"
msg_gamemode_change: "&fYour gamemode has been changed to &e%s&f!"

msg_fly_enabled: "&fYou can now fly! Remember, only for super emergencies. If you're using it outside of an emergency I will &oPERSONALLY SMITE YOU, &c&l&oYOU HEAR ME? &rOkay thank you!"
msg_fly_disabled: "&fThanks for disabling it. It's disabled."

msg_piano_help: "&fFirst do &e/piano menu &fand put the notes you would like to play into your hotbar. Then you can do &e/piano instrument &fand change your instrument! Finally, do &e/piano toggle &fto turn on the piano. Change your hotbar slot to the note you want to play!"
msg_piano_enabled: "&fThe piano has been enabled!"
msg_piano_disabled: "&fThe piano has been disabled! Hope you enjoyed!"
piano_menu_inventory_name: "Menu | The Floating City"
msg_piano_instrument_change: "&fYour piano instrument is now &e%s&f!"

msg_join: "&f%s joined the game."
msg_leave: "&f%s left the game."

msg_not_online: "&fThat player is not online."
msg_player_only: "&fYou must be a player to use this command."

msg_hat_set: "&fNow that's a fancy hat!"
msg_hat_removed: "&fGot your hat! I removed it. That's what I did."
msg_hat_none: "&fTo put on a hat, hold what you want to wear!"

msg_shrug: "&f%s &ashrugs \\_o¬o_/"
msg_blame: "&f%s &cblames &f%s"
msg_sue: "&f%s &cis suing &f%s"

msg_zap: "&f%s &czapped &f%s"
msg_zap_themself: "&f%s &czapped &fthemself"
msg_zap_everyone: "&f%s &czapped &feveryone"

msg_launch: "&f%s &alaunched &f%s"
msg_launch_themself: "&f%s &alaunched &fthemselves"
msg_launch_everyone: "&f%s &alaunched &feveryone"

msg_poke: "&f%s &cpoked &f%s"
msg_poke_themself: "&f%s &cpoked &fthemselves"
msg_poke_everyone: "&f%s &cpoked &feveryone"
poke_force:
  maxY: 0.8
  minY: 0.2
  maxXZ: 0.8
  minXZ: -0.8

msg_warp_first: "&fReaching maximum &6warp speed&f.."
msg_warp_second: "&fReaching maximum &cwarp speed&f.."
msg_warp_max: "&fMaximum &4warp speed &freached!"



