name: ${name}
version: ${version}
main: ${mainClass}

description: ${description}
author: ${author}
website: ${url}

api-version: 1.16

permissions:
  tfcplugin.chatcolor:
    description: Permission to color chat text.
    default: op
  tfcplugin.build:
    description: Permission to interact with the world.
    default: op
