name: ${name}
version: ${version}
description: ${description}
load: POSTWORLD
author: ${author}
website: ${url}
main: ${mainClass}
depend: []
database: false
api-version: 1.16
commands: {} # Thanks, ACF!
permissions:
  tfcplugin.chatcolor:
    description: Permission to color chat text.
    default: op
  tfcplugin.signcolor:
    description: Permission to color sign text.
    default: op
  tfcplugin.build:
    description: Permission to interact with the world.
    default: op