name: ${name}
version: ${version}
description: ${description}
load: POSTWORLD
author: ${author}
website: ${url}
main: ${mainClass}
depend: []
database: false
api-version: 1.12
commands: {} # Thanks, ACF!
permissions:
  tfcplugin.chatcolor:
    description: Permission to color chat text.
    default: op
  tfcplugin.signcolor:
    description: Permission to color sign text.
    default: op
  tfcplugin.build:
    description: Permission to interact with the world.
    default: op
  tfcplugin.*:
    description: Complete permission to all of TFCPlugin.
    default: op
    children:
      tfcplugin.chatcolor: true
      tfcplugin.signcolor: true
      tfcplugin.build: true